In [1]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[0][2]

3

In [2]:
aar2d[0,2]

NameError: name 'aar2d' is not defined

In [3]:
arr2d[0,2]

3

In [5]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [7]:
languages =  [ 'Mandarin ', 'Spanish', 'English', 'Hindi', 'Arabic', 'Portuguese', 'Bengali', 'Russian', 'Japanese', 'Punjabi' ]

speakers = [ 955, 405, 360, 310, 295, 215, 205, 155, 125, 100 ]

langnp   =  np.array(languages)
speaknp  = np.array(speakers, dtype=int)
speaknp >= 300

array([ True,  True,  True,  True, False, False, False, False, False, False], dtype=bool)

In [9]:
speaknp[speaknp >= 300]

array([955, 405, 360, 310])

In [10]:
languages == 'English'

False